config/routes.rb
Rails.application.routes.draw do
  root to: "application#welcome"

  devise_for :users

  # ---------------------------
  # -        Skippers         -
  # ---------------------------

  resources :skippers

  # Route for detaching a city from the given skipper.
  post "/skippers/:id/detach_city", to: "skippers#detach_city", as: :detach_city

  # ---------------------------
  # -         Cities          -
  # ---------------------------

  resources :cities

  # Route for showing the attaching form for skippers.
  get "/cities/:id/attach_skipper", to: "cities#show_attach_skipper"

  # Route for attaching a skipper to the given city.
  post "/cities/:id/attach_skipper", to: "cities#attach_skipper"

  # ---------------------------
  # -        Passages         -
  # ---------------------------

  resources :passages

  # Route for showing the attaching form for cargos.
  get "/passages/:id/attach_cargo", to: "passages#show_attach_cargo"

  # Route for attaching a cargo to the given city.
  post "/passages/:id/attach_cargo", to: "passages#attach_cargo"

  # Route for detaching a city which the passage is from.
  post "/passages/:id/detach_from_city", to: "passages#detach_from_city", as: :detach_from_city

  # Route for detaching a city which the passage is going to.
  post "/passages/:id/detach_to_city", to: "passages#detach_to_city", as: :detach_to_city

  # ---------------------------
  # -         Goods           -
  # ---------------------------

  resources :goods

  # ---------------------------
  # -         Cargo           -
  # ---------------------------

  resources :cargo

  # ---------------------------
  # -       API Routes        -
  # ---------------------------

  namespace :api do
    # Index for cities
    get "/cities", to: "cities#index"

    # Showing a single city
    get "/cities/:id", to: "cities#show"
  end
end

app/models/good.rb
class Good < ApplicationRecord
    self.inheritance_column = 'inheritance_type'

    has_many :cargo
    has_many :passages, through: :cargo, dependent: :destroy
end

app/controllers/goods_controller.rb
##
# A controller class for the goods model.

class GoodsController < ApplicationController
  before_action :authenticate_user!

  ##
  # Shows all goods from the database on a view.

  def index
    @goods = Good.all
  end

  ##
  # Shows a single good from the database on a view.

  def show
    @good = Good.find(params[:id])
  end

  ##
  # Creates a new instance of a good and shows the form.

  def new
    @good = Good.new
  end

  ##
  # Creates a new good in the database and redirects to the the show view of that good.

  def create
    @good = Good.new(validate_params)

    if @good.save
      redirect_to @good
    else
      render :new, status: :unprocessable_entity
    end
  end

  ##
  # Finds the correct instance that needs to be updated and shows the update form.

  def edit
    @good = Good.find(params[:id])
  end

  ##
  # Checks if the parameters are valid and updates the instance.

  def update
    @good = Good.find(params[:id])

    if @good.update(validate_params)
      redirect_to @good
    else
      render :edit, status: :unprocessable_entity
    end
  end

  ##
  # Deletes the given good from the database.
  
  def destroy
    @good = Good.find(params[:id])
    @good.destroy

    redirect_to root_path, status: :see_other
  end

  ##
  # Validates the incoming parameters of the form.

  private def validate_params
    params.require(:good).permit(:type)
  end
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/views/goods/_form.html.erb
<%= form_with model: good do |form| %>
    <div class="my-4">
        <%= form.label :type, "Type" %>
        <%= form.text_field :type, class: "block bg-white w-full lg:w-1/2 border border-slate-300 rounded-md py-2 px-2 shadow-sm focus:outline-none focus:border-primary focus:ring-primary focus:ring-1" %>
    </div>

    <%= form.submit "Goed toevoegen", class: "bg-primary rounded-lg text-white p-4 w-full lg:w-auto cursor-pointer font-bold" %>
<% end %>

app/views/goods/edit.html.erb
<!-- Heading -->
<%= render "partials/heading", backlink: true, title: "Goed wijzigen: #{@good.type}" %>

<!-- Form -->
<%= render "form", good: @good %>

app/views/goods/index.html.erb
<%= render "partials/heading", backlink: true, title: "Goederen", create_url: "/goods/new" %>

<div class="bg-white rounded-lg mt-4 px-4">
    <% if @goods.size != 0 %>
        <table class="bg-white rounded-lg w-full">
            <tr class="h-12">
                <th class="text-left">ID</th>
                <th class="text-left">Type</th>
                <th class="text-left">Acties</th>
            </tr>

            <% @goods.each do |good| %>
                <tr class="h-12 border-y">
                    <td><a class="text-blue-500 font-bold" href="<%= good_path(good) %>" alt="Goed bekijken"><%= good.id %></a></td>
                    <td><%= good.type %></td>
                    
                    <td>
                        <%= link_to image_tag("edit_icon.svg", class: "h-5"), edit_good_path(good), class: "bg-blue-300 rounded-lg inline-block p-2" %>
                        
                        <%= link_to image_tag("trash_icon.svg", class: "h-5"), good_path(good), data: {
                            turbo_method: :delete,
                            turbo_confirm: "Weet u zeker dat u dit goed wilt verwijderen?"
                        }, class: "bg-red-500 rounded-lg inline-block p-2" %>
                    </td>
                </tr>
            <% end %>
        </table>
    <% else %>
        <p class="text-center">Er zijn nog geen goederen toegevoegd.</p>
    <% end %>
</div>

app/views/goods/new.html.erb
<%= render "partials/heading", backlink: true, title: "Goed toevoegen" %>

<%= render "form", good: @good %>

app/views/goods/show.html.erb
<!-- Heading -->
<%= render "partials/heading", backlink: true, title: "Goed: #{@good.type}", is_show: true, model: @good, model_path: "/goods" %>

<div class="bg-white w-full p-4 rounded-lg mt-4">
    <!-- Type of good -->
    <%= render "partials/field_value", label: "Type", value: @good.type %>
</div>

<h2 class="text-xl font-bold mt-4">Doorvaarten</h2>

<div class="bg-white rounded-lg mt-2 px-4">
    <% if @good.cargo.size != 0 %>
        <table class="bg-white rounded-lg w-full">
            <tr class="h-12">
                <th class="text-left">ID</th>
                <th class="text-left">Volgnummer doorvaart</th>
                <th class="text-left">Maat</th>
                <th class="text-left">Aantal eenheden</th>
                <th class="text-left">Acties</th>
            </tr>

            <% @good.cargo.each do |cargo| %>
                <tr class="h-12 border-y">
                    <td><%= cargo.id %></a></td>
                    <td><a class="text-blue-500 font-bold" href="<%= passage_path(cargo.passage) %>" alt="Doorvaart bekijken"><%= cargo.passage.serial_number %></a></td>
                    <td><%= cargo.measure %></td>
                    <td><%= cargo.number_of_units %></td>
                    
                    <td>
                        <%= link_to image_tag("edit_icon.svg", class: "h-5"), edit_cargo_path(cargo), class: "bg-blue-300 rounded-lg inline-block p-2" %>
                        
                        <%= link_to image_tag("trash_icon.svg", class: "h-5"), cargo_path(cargo), data: {
                            turbo_method: :delete,
                            turbo_confirm: "Weet u zeker dat u deze lading wilt ontkoppelen?"
                        }, class: "bg-red-500 rounded-lg inline-block p-2" %>
                    </td>
                </tr>
            <% end %>
        </table>
    <% else %>
        <p class="py-4">Er zijn nog geen doorvaarten gekoppeld.</p>
    <% end %>
</div>