config/routes.rb
Rails.application.routes.draw do
  root to: "application#welcome"

  devise_for :users

  # ---------------------------
  # -        Skippers         -
  # ---------------------------

  resources :skippers

  # Route for detaching a city from the given skipper.
  post "/skippers/:id/detach_city", to: "skippers#detach_city", as: :detach_city

  # ---------------------------
  # -         Cities          -
  # ---------------------------

  resources :cities

  # Route for showing the attaching form for skippers.
  get "/cities/:id/attach_skipper", to: "cities#show_attach_skipper"

  # Route for attaching a skipper to the given city.
  post "/cities/:id/attach_skipper", to: "cities#attach_skipper"

  # ---------------------------
  # -        Passages         -
  # ---------------------------

  resources :passages

  # Route for showing the attaching form for cargos.
  get "/passages/:id/attach_cargo", to: "passages#show_attach_cargo"

  # Route for attaching a cargo to the given city.
  post "/passages/:id/attach_cargo", to: "passages#attach_cargo"

  # Route for detaching a city which the passage is from.
  post "/passages/:id/detach_from_city", to: "passages#detach_from_city", as: :detach_from_city

  # Route for detaching a city which the passage is going to.
  post "/passages/:id/detach_to_city", to: "passages#detach_to_city", as: :detach_to_city

  # ---------------------------
  # -         Goods           -
  # ---------------------------

  resources :goods

  # ---------------------------
  # -         Cargo           -
  # ---------------------------

  resources :cargo

  # ---------------------------
  # -       API Routes        -
  # ---------------------------

  namespace :api do
    # Index for cities
    get "/cities", to: "cities#index"

    # Showing a single city
    get "/cities/:id", to: "cities#show"
  end
end

app/models/passage.rb
class Passage < ApplicationRecord
    # Relation with goods table using an association table called "cargos".
    has_many :cargo
    has_many :goods, through: :cargo, dependent: :destroy

    # Relation with skippers table.
    belongs_to :skipper

    # Relation with cities table.
    belongs_to :from_city, class_name: 'City', optional: true
    belongs_to :to_city, class_name: 'City', optional: true

    # Validation.
    validates :skipper_id, presence: true
    validates :tonnage, presence: true
    validates :serial_number, presence: true

    ##
    # Converts the current instance of City to a simple JSON object.

    def to_json()
        return {
            "shipment_number": serial_number,
            "skipper_name": skipper.name,
            "distance": "[FILL]",
            "departure_date": "[FILL]",
            "arrival_date": "[FILL]",
            "main_cargo": "[FILL]",
            "main_route": "[FILL]"
        }
    end
end

app/controllers/passages_controller.rb
## 
# A controller class for the passages model.

class PassagesController < ApplicationController
  before_action :authenticate_user!

  ##
  # Shows all passages from the database on a view.
  
  def index
    @passages = Passage.all
  end

  ##
  # Shows a single passage from the database on a view.

  def show
    @passage = Passage.find(params[:id])
  end

  ##
  # Creates a new instance of a passage and shows the form.

  def new
    @passage = Passage.new
  end

  ##
  # Creates a new passage in the database and redirects to the the show view of that passage.

  def create
    @passage = Passage.new(validate_params)

    if @passage.save
      redirect_to @passage
    else
      render :new, status: :unprocessable_entity
    end
  end

  ##
  # Finds the correct instance that needs to be updated and shows the update form.

  def edit
    @passage = Passage.find(params[:id])
  end

  ##
  # Checks if the parameters are valid and updates the instance.

  def update
    @passage = Passage.find(params[:id])

    if @passage.update(validate_params)
      redirect_to @passage
    else
      render :edit, status: :unprocessable_entity
    end
  end

  ##
  # Shows the attach form for attaching a new cargo to a passage.

  def show_attach_cargo()
    @passage = Passage.find(params[:id])
  end

  ##
  # Attaches a new cargo to the given passage.

  def attach_cargo()
    @passage = Passage.find(params[:id])

    if @passage.cargo.create(good_id: params[:good_id], measure: params[:measure], number_of_units: params[:number_of_units])
      redirect_to @passage
    else
      render :show_attach_cargo, status: :unprocessable_entity
    end
  end

  ##
  # Detaches the given city which the passage is from.
  
  def detach_from_city
    @passage = Passage.find(params[:id])
    from_city = @passage.from_city
    
    if @passage.update(:from_city_id => nil)
      redirect_to from_city
    else
      render :new, status: :unprocessable_entity
    end
  end

  ##
  # Detaches the given city which the passage is going to.
  
  def detach_to_city
    @passage = Passage.find(params[:id])
    to_city = @passage.to_city
    
    if @passage.update(:to_city_id => nil)
      redirect_to to_city
    else
      render :new, status: :unprocessable_entity
    end
  end

  ##
  # Deletes the given passage from the database.
  
  def destroy
    @passage = Passage.find(params[:id])
    @passage.destroy

    redirect_to root_path, status: :see_other
  end

  ##
  # Validates the query parameters.

  private def validate_params
    params.require(:passage).permit!
  end
end

app/helpers/passages_helper.rb
module PassagesHelper
end

app/views/passages/_form.html.erb
<%= form_with model: passage do |form| %>
    <!-- Skipper dropdown -->
    <%= render "partials/dropdown", form: form, value: :skipper_id, label: "Schipper", required: true, items: Skipper.order(:name), item_value: :id, item_label: :name %>

    <!-- From city dropdown -->
    <%= render "partials/dropdown", form: form, value: :from_city_id, label: "Plaats van afkomst", required: false, items: City.order(:name), item_value: :id, item_label: :name %>
    
    <!-- To city dropdown -->
    <%= render "partials/dropdown", form: form, value: :to_city_id, label: "Plaats van bestemming", required: false, items: City.order(:name), item_value: :id, item_label: :name %>

    <!-- Tonnage input -->
    <%= render "partials/input", form: form, value: :tonnage, label: "Tonnage", required: true, model: passage %>

    <!-- Serial number input -->
    <%= render "partials/input", form: form, value: :serial_number, label: "Volgnummer", required: true, model: passage %>

    <!-- Total coin type 1 input -->
    <%= render "partials/input", form: form, value: :total_coin_type_1, label: "Totaal muntsoort 1", required: false, model: passage %>

    <!-- Total amount 1 input -->
    <%= render "partials/input", form: form, value: :total_amount_1, label: "Totaal bedrag 1", required: false, model: passage %>

    <!-- Total coin type 2 input -->
    <%= render "partials/input", form: form, value: :total_coin_type_2, label: "Totaal muntsoort 2", required: false, model: passage %>

    <!-- Total amount 2 input -->
    <%= render "partials/input", form: form, value: :total_amount_2, label: "Totaal bedrag 2", required: false, model: passage %>

    <!-- Total coin type 3 input -->
    <%= render "partials/input", form: form, value: :total_coin_type_3, label: "Totaal muntsoort 3", required: false, model: passage %>

    <!-- Total amount 3 input -->
    <%= render "partials/input", form: form, value: :total_amount_3, label: "Totaal bedrag 3", required: false, model: passage %>

    <!-- Total coin type 4 input -->
    <%= render "partials/input", form: form, value: :total_coin_type_4, label: "Totaal muntsoort 4", required: false, model: passage %>

    <!-- Total amount 4 input -->
    <%= render "partials/input", form: form, value: :total_amount_4, label: "Totaal bedrag 4", required: false, model: passage %>

    <!-- Total coin type 5 input -->
    <%= render "partials/input", form: form, value: :total_coin_type_5, label: "Totaal muntsoort 5", required: false, model: passage %>

    <!-- Total amount 5 input -->
    <%= render "partials/input", form: form, value: :total_amount_5, label: "Totaal bedrag 5", required: false, model: passage %>

    <%= form.submit "Doorvaart toevoegen", class: "bg-primary rounded-lg text-white p-4 w-full lg:w-auto cursor-pointer font-bold" %>
<% end %>

app/views/passages/edit.html.erb
<!-- Heading -->
<%= render "partials/heading", backlink: true, title: "Doorvaart wijzigen: #{@passage.serial_number}" %>

<!-- Form -->
<%= render "form", passage: @passage %>

app/views/passages/index.html.erb
<!-- Heading -->
<%= render "partials/heading", backlink: true, title: "Doorvaarten", create_url: "/passages/new" %>

<div class="bg-white rounded-lg mt-2 px-4">
    <% if @passages.size != 0 %>
        <table class="bg-white rounded-lg w-full mt-4">
            <tr class="h-12">
                <th class="text-left">ID</th>
                <th class="text-left">Volgnummer</th>
                <th class="text-left">Schipper</th>
                <th class="text-left">Van</th>
                <th class="text-left">Naar</th>
                <th class="text-left">Acties</th>
            </tr>

            <% @passages.each do |passage| %>
                <tr class="h-12 border-y">
                    <td><a class="text-blue-500 font-bold" href="<%= passage_path(passage) %>" alt="Doorvaart bekijken"><%= passage.id %></a></td>
                    <td><%= passage.serial_number %></td>
                    <td><%= passage.skipper.name %></td>
                    <td><%= passage.from_city != nil ? passage.from_city.name : "Onbekend" %></td>
                    <td><%= passage.to_city != nil ? passage.to_city.name : "Onbekend" %></td>
                    
                    <td>
                        <%= link_to image_tag("edit_icon.svg", class: "h-5"), edit_passage_path(passage), class: "bg-blue-300 rounded-lg inline-block p-2" %>
                        
                        <%= link_to image_tag("trash_icon.svg", class: "h-5"), passage_path(passage), data: {
                            turbo_method: :delete,
                            turbo_confirm: "Weet u zeker dat u deze doorvaart wilt verwijderen?"
                        }, class: "bg-red-500 rounded-lg inline-block p-2" %>
                    </td>
                </tr>
            <% end %>
        </table>
    <% else %>
        <div class="bg-white my-4 py-4 rounded-lg">
            <p>Er zijn geen doorvaarten bekend.</p>
        </div>
    <% end %>
</div>

app/views/passages/new.html.erb
<%= render "partials/heading", backlink: true, title: "Doorvaart toevoegen" %>

<%= render "form", passage: @passage %>

app/views/passages/show.html.erb
<!-- Heading with backbutton -->
<%= render "partials/heading", backlink: true, title: "Doorvaart: #{@passage.serial_number}", is_show: true, model: @passage, model_path: "/passages" %>

<div class="bg-white w-full p-4 rounded-lg my-4">
    <!-- Skipper name -->
    <%= render "partials/field_value", label: "Schipper", value: @passage.skipper.name %>

    <!-- From city -->
    <%= render "partials/field_value", label: "Van", value: @passage.from_city != nil ? @passage.from_city.name : "Er is geen plaats van afkomst bekend." %>

    <!-- To city -->
    <%= render "partials/field_value", label: "Naar", value: @passage.to_city != nil ? @passage.to_city.name : "Er is geen bestemming bekend." %>

    <!-- Tonnage -->
    <%= render "partials/field_value", label: "Tonnage", value: @passage.tonnage %>

    <!-- Serial number -->
    <%= render "partials/field_value", label: "Volgnummer", value: @passage.serial_number %>

    <!-- Total coin type 1 -->
    <%= render "partials/field_value", label: "Totaal muntsoort 1", value: @passage.total_coin_type_1 %>

    <!-- Total amount 1 -->
    <%= render "partials/field_value", label: "Totaal bedrag 1", value: @passage.total_amount_1 %>

    <!-- Total coin type 2 -->
    <%= render "partials/field_value", label: "Totaal muntsoort 2", value: @passage.total_coin_type_2 %>

    <!-- Total amount 2 -->
    <%= render "partials/field_value", label: "Totaal bedrag 2", value: @passage.total_amount_2 %>

    <!-- Total coin type 3 -->
    <%= render "partials/field_value", label: "Totaal muntsoort 3", value: @passage.total_coin_type_3 %>

    <!-- Total amount 3 -->
    <%= render "partials/field_value", label: "Totaal bedrag 3", value: @passage.total_amount_3 %>

    <!-- Total coin type 4 -->
    <%= render "partials/field_value", label: "Totaal muntsoort 4", value: @passage.total_coin_type_4 %>

    <!-- Total amount 4 -->
    <%= render "partials/field_value", label: "Totaal bedrag 4", value: @passage.total_amount_4 %>

    <!-- Total coin type 5 -->
    <%= render "partials/field_value", label: "Totaal muntsoort 5", value: @passage.total_coin_type_5 %>

    <!-- Total amount 5 -->
    <%= render "partials/field_value", label: "Totaal bedrag 5", value: @passage.total_amount_5 %>
</div>

<!-- Goods heading -->
<%= render "partials/heading", title: "Goederen aan boord", associations: true, create_url: "/passages/#{@passage.id}/attach_cargo" %>

<div class="bg-white rounded-lg mt-2 px-4">
    <% if @passage.cargo.size != 0 %>
        <table class="bg-white rounded-lg w-full">
            <tr class="h-12">
                <th class="text-left">ID</th>
                <th class="text-left">Type</th>
                <th class="text-left">Maat</th>
                <th class="text-left">Aantal eenheden</th>
                <th class="text-left">Acties</th>
            </tr>

            <% @passage.cargo.each do |cargo| %>
                <tr class="h-12 border-y">
                    <td><%= cargo.id %></td>
                    <td><a class="text-blue-500 font-bold" href="<%= good_path(cargo.good.id) %>" alt="Goed bekijken"><%= cargo.good.type %></td>
                    <td><%= cargo.measure %></td>
                    <td><%= cargo.number_of_units %></td>
                    
                    <td>
                        <%= link_to image_tag("edit_icon.svg", class: "h-5"), edit_cargo_path(cargo), class: "bg-blue-300 rounded-lg inline-block p-2" %>
                        
                        <%= link_to image_tag("trash_icon.svg", class: "h-5"), cargo_path(cargo), data: {
                            turbo_method: :delete,
                            turbo_confirm: "Weet u zeker dat u deze lading wilt ontkoppelen?"
                        }, class: "bg-red-500 rounded-lg inline-block p-2" %>
                    </td>
                </tr>
            <% end %>
        </table>
    <% else %>
        <div class="bg-white my-4 py-4 rounded-lg">
            <p>Er zijn geen goederen bekend.</p>
        </div>
    <% end %>
</div>

app/views/passages/show_attach_cargo.html.erb
<!-- Heading -->
<%= render "partials/heading", backlink: true, title: "Goed koppelen aan #{@passage.serial_number}" %>

<%= form_with url: "/passages/#{@passage.id}/attach_cargo", method: "post" do |form| %>
    <!-- Good to attach dropdown -->
    <%= render "partials/dropdown", form: form, value: :good_id, label: "Goed", required: false, items: Good.order(:type), item_value: :id, item_label: :type %>

    <!-- Measure input -->
    <%= render "partials/input", form: form, value: :measure, label: "Maat", required: true, model: @passage %>

    <!-- Number of units input -->
    <%= render "partials/input", form: form, value: :number_of_units, label: "Aantal eenheden", required: true, model: @passage %>

    <%= form.submit "Goed koppelen", class: "bg-primary rounded-lg text-white p-4 w-full lg:w-auto cursor-pointer font-bold" %>
<% end %>