config/routes.rb
Rails.application.routes.draw do
  root to: "application#welcome"

  devise_for :users

  # ---------------------------
  # -        Skippers         -
  # ---------------------------

  resources :skippers

  # Route for detaching a city from the given skipper.
  post "/skippers/:id/detach_city", to: "skippers#detach_city", as: :detach_city

  # ---------------------------
  # -         Cities          -
  # ---------------------------

  resources :cities

  # Route for showing the attaching form for skippers.
  get "/cities/:id/attach_skipper", to: "cities#show_attach_skipper"

  # Route for attaching a skipper to the given city.
  post "/cities/:id/attach_skipper", to: "cities#attach_skipper"

  # ---------------------------
  # -        Passages         -
  # ---------------------------

  resources :passages

  # Route for showing the attaching form for cargos.
  get "/passages/:id/attach_cargo", to: "passages#show_attach_cargo"

  # Route for attaching a cargo to the given city.
  post "/passages/:id/attach_cargo", to: "passages#attach_cargo"

  # Route for detaching a city which the passage is from.
  post "/passages/:id/detach_from_city", to: "passages#detach_from_city", as: :detach_from_city

  # Route for detaching a city which the passage is going to.
  post "/passages/:id/detach_to_city", to: "passages#detach_to_city", as: :detach_to_city

  # ---------------------------
  # -         Goods           -
  # ---------------------------

  resources :goods

  # ---------------------------
  # -         Cargo           -
  # ---------------------------

  resources :cargo

  # ---------------------------
  # -       API Routes        -
  # ---------------------------

  namespace :api do
    # Index for cities
    get "/cities", to: "cities#index"

    # Showing a single city
    get "/cities/:id", to: "cities#show"
  end
end

app/models/city.rb
class City < ApplicationRecord
    # Relations for from and to cities.
    has_many :from_passages, class_name: 'Passage', foreign_key: 'from_city_id', dependent: :nullify
    has_many :to_passages, class_name: 'Passage', foreign_key: 'to_city_id', dependent: :nullify

    # Relation for skippers
    has_many :skippers, dependent: :nullify

    # Validations
    validates :name, :latitude, :longitude, presence: true

    ##
    # Converts the current instance of City to a simple JSON object.

    def to_simple_json()
        return {
            "id": id,
            "name": name,
            "latitude": latitude,
            "longitude": longitude
        }
    end

    ##
    # Converts the current instance of City to a detailed JSON object.

    def to_detailed_json()
        captains = []
        routes = []

        # Loop through the skippers to convert to JSON.
        skippers.each do |skipper|
            captains.append(skipper.to_json)
        end

        # Loop through the from passages to convert to JSON.
        from_passages.each do |passage|
            routes.append(passage.to_json)
        end

        return {
            "id": id,
            "name": name,
            "captains": captains,
            "routes": routes
        }
    end
end

app/controllers/api/cities_controller.rb
##
# An API controller class for the cities model.

class Api::CitiesController < ApplicationController
    ##
    # Renders all cities in JSON format.
    
    def index
        cities = City.all
        response = []
        
        # Loop through all cities.
        cities.each do |city|
            response.append(city.to_simple_json)
        end

        render json: response
    end

    ##
    # Renders a single city in JSON format.
    
    def show
        city = City.find(params[:id])
        render json: city.to_detailed_json
    end
end

app/controllers/cities_controller.rb
##
# A controller class for the cities model.

class CitiesController < ApplicationController
  before_action :authenticate_user!

  ##
  # Shows all cities from the database on a view.

  def index
    @cities = City.all
  end

  ##
  # Shows a single city from the database on a view.

  def show
    @city = City.find(params[:id])
  end

  ##
  # Creates a new instance of a city and shows the form.

  def new
    @city = City.new
  end

  ##
  # Creates a new city in the database and redirects to the the show view of that city.

  def create
    @city = City.new(validate_params)

    if @city.save
      redirect_to @city
    else
      render :new, status: :unprocessable_entity
    end
  end

  ##
  # Finds the correct instance that needs to be updated and shows the update form.

  def edit
    @city = City.find(params[:id])
  end

  ##
  # Checks if the parameters are valid and updates the instance.

  def update
    @city = City.find(params[:id])

    if @city.update(validate_params)
      redirect_to @city
    else
      render :edit, status: :unprocessable_entity
    end
  end

  ##
  # Deletes the given city from the database.
  
  def destroy
    @city = City.find(params[:id])
    @city.destroy

    redirect_to root_path, status: :see_other
  end

  ##
  # Shows the attach form for attaching a new skipper to a city.

  def show_attach_skipper()
    @city = City.find(params[:id])
  end

  ##
  # Attaches a new skipper to the given city.

  def attach_skipper()
    @city = City.find(params[:id])

    if @city.skippers << Skipper.find(params[:skipper_id])
      redirect_to @city
    else
      render :show_attach_skipper, status: :unprocessable_entity
    end
  end

  ##
  # Validates the query parameters.

  private def validate_params
    params.require(:city).permit!
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_form.html.erb
<%= form_with model: city do |form| %>
    <!-- Name input -->
    <%= render "partials/input", form: form, value: :name, label: "Naam", required: true, model: city %>
    
    <!-- Latitude input -->
    <%= render "partials/input", form: form, value: :latitude, label: "Breedtegraad (latitude)", required: true, model: city %>

    <!-- Longitude input -->
    <%= render "partials/input", form: form, value: :longitude, label: "Lengtegraad (longitude)", required: true, model: city %>

    <%= form.submit "Stad toevoegen", class: "bg-primary rounded-lg text-white p-4 w-full lg:w-auto cursor-pointer font-bold" %>
<% end %>

app/views/cities/edit.html.erb
<!-- Heading -->
<%= render "partials/heading", backlink: true, title: "Stad wijzigen: #{@city.name}" %>

<!-- Form -->
<%= render "form", city: @city %>

app/views/cities/index.html.erb
<%= render "partials/heading", backlink: true, title: "Steden", create_url: "/cities/new" %>

<div class="bg-white rounded-lg mt-4 px-4">
    <% if @cities.size != 0 %>
        <table class="bg-white rounded-lg w-full">
            <tr class="h-12">
                <th class="text-left">ID</th>
                <th class="text-left">Naam</th>
                <th class="text-left">Breedtegraad (latitude)</th>
                <th class="text-left">Lengtegraad (longitude)</th>
                <th class="text-left">Acties</th>
            </tr>

            <% @cities.each do |city| %>
                <tr class="h-12 border-y">
                    <td><a class="text-blue-500 font-bold" href="<%= city_path(city) %>" alt="Stad bekijken"><%= city.id %></a></td>
                    <td><%= city.name %></td>
                    <td><%= city.latitude %></td>
                    <td><%= city.longitude %></td>
                    
                    <td>
                        <%= link_to image_tag("edit_icon.svg", class: "h-5"), edit_city_path(city), class: "bg-blue-300 rounded-lg inline-block p-2" %>
                        
                        <%= link_to image_tag("trash_icon.svg", class: "h-5"), city_path(city), data: {
                            turbo_method: :delete,
                            turbo_confirm: "Weet u zeker dat u deze stad wilt verwijderen?"
                        }, class: "bg-red-500 rounded-lg inline-block p-2" %>
                    </td>
                </tr>
            <% end %>
        </table>
    <% else %>
        <p class="text-center">Er zijn nog geen steden toegevoegd.</p>
    <% end %>
</div>

app/views/cities/new.html.erb
<%= render "partials/heading", backlink: true, title: "Stad toevoegen" %>

<%= render "form", city: @city %>

app/views/cities/show.html.erb
<!-- Heading -->
<%= render "partials/heading", backlink: true, title: "Stad: #{@city.name}", is_show: true, model: @city, model_path: "/cities" %>

<div class="bg-white w-full p-4 rounded-lg my-4">
    <!-- City name -->
    <%= render "partials/field_value", label: "Naam", value: @city.name %>

    <!-- Latitude -->
    <%= render "partials/field_value", label: "Breedtegraad (latitude)", value: @city.latitude %>

    <!-- Longitude -->
    <%= render "partials/field_value", label: "Lengtegraad (longitude)", value: @city.longitude %>
</div>

<!-- Skippers heading -->
<%= render "partials/heading", title: "Schippers die hier vandaan komen", associations: true, create_url: "/cities/#{@city.id}/attach_skipper" %>

<div class="bg-white rounded-lg mt-2 px-4">
    <% if @city.skippers.size != 0 %>
        <table class="bg-white rounded-lg w-full">
            <tr class="h-12">
                <th class="text-left">ID</th>
                <th class="text-left">Naam</th>
                <th class="text-left">Acties</th>
            </tr>

            <% @city.skippers.each do |skipper| %>
                <tr class="h-12 border-y">
                    <td><a class="text-blue-500 font-bold" href="<%= skipper_path(skipper) %>" alt="Schipper bekijken"><%= skipper.id %></a></td>
                    <td><%= skipper.name %></td>
                    
                    <td>
                        <%= link_to image_tag("edit_icon.svg", class: "h-5"), edit_skipper_path(skipper), class: "bg-blue-300 rounded-lg inline-block p-2" %>
                        
                        <%= link_to image_tag("trash_icon.svg", class: "h-5"), detach_city_path(skipper), data: {
                            turbo_method: :post,
                            turbo_confirm: "Weet u zeker dat u deze schipper wilt ontkoppelen?"
                        }, class: "bg-red-500 rounded-lg inline-block p-2" %>
                    </td>
                </tr>
            <% end %>
        </table>
    <% else %>
        <div class="bg-white my-4 py-4 rounded-lg">
            <p>Er zijn geen schippers die hier vandaan komen.</p>
        </div>
    <% end %>
</div>

<!-- From passages heading -->
<%= render "partials/heading", title: "Doorvaarten die hier vandaan kwamen", associations: true %>

<div class="bg-white rounded-lg mt-2 px-4">
    <% if @city.from_passages.size != 0 %>
        <table class="bg-white rounded-lg w-full">
            <tr class="h-12">
                <th class="text-left">ID</th>
                <th class="text-left">Volgnummer</th>
                <th class="text-left">Schipper</th>
                <th class="text-left">Van</th>
                <th class="text-left">Naar</th>
                <th class="text-left">Acties</th>
            </tr>

            <% @city.from_passages.each do |passage| %>
                <tr class="h-12 border-y">
                    <td><a class="text-blue-500 font-bold" href="<%= passage_path(passage) %>" alt="Doorvaart bekijken"><%= passage.id %></a></td>
                    <td><%= passage.serial_number %></td>
                    <td><%= passage.skipper.name %></td>
                    <td><%= passage.from_city != nil ? passage.from_city.name : "Onbekend" %></td>
                    <td><%= passage.to_city != nil ? passage.to_city.name : "Onbekend" %></td>
                    
                    <td>
                        <%= link_to image_tag("edit_icon.svg", class: "h-5"), edit_passage_path(passage), class: "bg-blue-300 rounded-lg inline-block p-2" %>
                        
                        <%= link_to image_tag("trash_icon.svg", class: "h-5"), detach_from_city_path(passage), data: {
                            turbo_method: :post,
                            turbo_confirm: "Weet u zeker dat u deze doorvaart wilt ontkoppelen?"
                        }, class: "bg-red-500 rounded-lg inline-block p-2" %>
                    </td>
                </tr>
            <% end %>
        </table>
    <% else %>
        <div class="bg-white my-4 py-4 rounded-lg">
            <p>Er zijn geen doorvaart die hier vandaan komen.</p>
        </div>
    <% end %>
</div>

<!-- To passages heading -->
<%= render "partials/heading", title: "Doorvaarten die hier naartoe kwamen", associations: true %>

<div class="bg-white rounded-lg mt-2 px-4">
    <% if @city.to_passages.size != 0 %>
        <table class="bg-white rounded-lg w-full">
            <tr class="h-12">
                <th class="text-left">ID</th>
                <th class="text-left">Volgnummer</th>
                <th class="text-left">Schipper</th>
                <th class="text-left">Van</th>
                <th class="text-left">Naar</th>
                <th class="text-left">Acties</th>
            </tr>

            <% @city.to_passages.each do |passage| %>
                <tr class="h-12 border-y">
                    <td><a class="text-blue-500 font-bold" href="<%= passage_path(passage) %>" alt="Doorvaart bekijken"><%= passage.id %></a></td>
                    <td><%= passage.serial_number %></td>
                    <td><%= passage.skipper.name %></td>
                    <td><%= passage.from_city != nil ? passage.from_city.name : "Onbekend" %></td>
                    <td><%= passage.to_city != nil ? passage.to_city.name : "Onbekend" %></td>
                    
                    <td>
                        <%= link_to image_tag("edit_icon.svg", class: "h-5"), edit_passage_path(passage), class: "bg-blue-300 rounded-lg inline-block p-2" %>
                        
                        <%= link_to image_tag("trash_icon.svg", class: "h-5"), detach_to_city_path(passage), data: {
                            turbo_method: :post,
                            turbo_confirm: "Weet u zeker dat u deze doorvaart wilt ontkoppelen?"
                        }, class: "bg-red-500 rounded-lg inline-block p-2" %>
                    </td>
                </tr>
            <% end %>
        </table>
    <% else %>
        <div class="bg-white my-4 py-4 rounded-lg">
            <p>Er zijn geen doorvaart die hier vandaan komen.</p>
        </div>
    <% end %>
</div>

app/views/cities/show_attach_skipper.html.erb
<!-- Heading -->
<%= render "partials/heading", backlink: true, title: "Schipper koppelen aan #{@city.name}" %>

<%= form_with url: "/cities/#{@city.id}/attach_skipper", method: "post" do |form| %>
    <!-- Skipper to attach dropdown -->
    <%= render "partials/dropdown", form: form, value: :skipper_id, label: "Schipper", required: false, items: Skipper.order(:name), item_value: :id, item_label: :name %>

    <%= form.submit "Schipper koppelen", class: "bg-primary rounded-lg text-white p-4 w-full lg:w-auto cursor-pointer font-bold" %>
<% end %>